name: CI

on: 
  push: 
    branches: main
  pull_request: 
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs: 
  build: #name of the job
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v5 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multiline script
        run: | 
          echo Add other actions
          echo to build and test your project
      
